### ISSUE TITLE
route driven favicon

### ISSUE THREAD

**Issue by valorloff** [VeliovGroup/Meteor-flow-router-meta#11]
Thanks for your usefully job! 
Is it right way to define different route based favicons?
```js
FlowRouter.route('/admin/orders', {
  name: 'orders',
  title:'Orders',
    link: {
        favicon: {
            rel: 'shortcut icon',
            href: '/img/orders.png'
        }
    },
```
In my setup favicons don't changed with next routes and in view source i noticed same

```html
<head>
<link rel="stylesheet" type="text/css" class="__meteor-css__" href="/merged-stylesheets.css?hash=8522f7d30d4fd02d7140d385c697b968bad9ac26">
```
Thanks in advance

**Comment by dr-dimitru** [comment]
Hey @valorloff ,

Thank you for reporting this, I'm very sorry it took a month to reply.
We have run some test and added this case to out test-suit:
 - [Release `v2.0.14`](https://github.com/VeliovGroup/Meteor-flow-router-meta/releases/tag/2.0.14)
 - [`favicon` setup example](https://github.com/VeliovGroup/Meteor-flow-router-meta/blob/master/tests.js#L79-L82)

Let me know if it works on your end.
Feel free to reopen it in case if the issue is still persists on your end.
